### PR TITLE
Feat/int 537 new languages and translations

### PR DESCRIPTION
**Pull request by syjust-alma**

### CODE REVIEW

**Comment by PaulRouss3l** [comment]
does this script work on windows ?

**Review by PaulRouss3l — APPROVED** [review]

**Review by Francois-Gomis — APPROVED** [review]
remove pt_PT ?

**Comment by syjust-alma** [comment]
> does this script work on windows ?

nope

**Comment by syjust-alma** [comment]
> remove pt_PT ?

we `pt_PT` seem's fully proofread in crowdin, we can publish it 😉

**Pull request merged**
